version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:5000"
    volumes:
      - db_data:/app/database
    environment:
      - FLASK_ENV=development

volumes:
  postgres_data:
  db_data:
